DEVGRPCACHE='zenconf/devgrpcache.ini'
web_services =  { '1min Loadavg': 'loadavg_1min', 'Cpu Idle Pct': 'cpu_ssCpuIdle' }
queue_services = { '1min Loadavg': 'loadavg_1min',  'MongoS cmd/s': 'MongoStats_commands', 'MongoS q/s': 'MongoStats_querys', 'MongoS conns/s': 'MongoStats_conns' }
docbase1_services = { '1min Loadavg': 'loadavg_1min', 'MongoD cmd/s': 'MongoD_Stats_commands', 'MongoD q/s': 'MongoD_Stats_querys', 'MongoD conns/s': 'MongoD_Stats_conns' }
webdocbase_services = { '1min Loadavg': 'loadavg_1min', 'Mongo cmd/s': 'MongoStats_commands', 'Mongo q/s': 'MongoStats_querys', 'Mongo conns/s': 'MongoStats_conns' }
webonly_services = { 'Apache CPU Load': 'apache_cpuLoad', 'Apache Busy Slots': 'apache_slotSendingReply'}
queue_services = { 'Corejobs Low':'CheckQueue_corejobs_low','Corejobs Medium':'CheckQueue_corejobs_medium','Corejobs High':'CheckQueue_corejobs_high'}
queues_services = { }
queuem_services = {'Corejobs Low':'CheckQueue_corejobs_low','Corejobs Medium':'CheckQueue_corejobs_medium','Corejobs High':'CheckQueue_corejobs_high'}
search_services = { 'JMX Heap used': 'JMX Heap Memory_used', 'JMX Heap max': 'JMX Heap Memory_max','JMX Files': 'JMX Open File Descriptors_OpenFiles','JMX Threads': 'JMX Thread Count_ThreadCount'}
basic_services =  { '1min Loadavg': 'loadavg_1min', 'Cpu Idle Pct': 'cpu_ssCpuIdle' }
asx_services =  { '1min Loadavg': 'loadavg_1min', 'Cpu Idle Pct': 'cpu_ssCpuIdle' }
qas_services =  { '1min Loadavg': 'loadavg_1min', 'Cpu Idle Pct': 'cpu_ssCpuIdle' }
dev_services =  { '1min Loadavg': 'loadavg_1min', 'Cpu Idle Pct': 'cpu_ssCpuIdle' }
awr_services =  { '1min Loadavg': 'loadavg_1min', 'Cpu Idle Pct': 'cpu_ssCpuIdle' }
pup_services =  { '1min Loadavg': 'loadavg_1min', 'Cpu Idle Pct': 'cpu_ssCpuIdle' }
dbs_services =  { '1min Loadavg': 'loadavg_1min', 'Cpu Idle Pct': 'cpu_ssCpuIdle' }
ser_services =  { '1min Loadavg': 'loadavg_1min', 'Cpu Idle Pct': 'cpu_ssCpuIdle' }
cms_services =  { '1min Loadavg': 'loadavg_1min', 'Cpu Idle Pct': 'cpu_ssCpuIdle' }
kss_services =  { '1min Loadavg': 'loadavg_1min', 'Cpu Idle Pct': 'cpu_ssCpuIdle' }
adm_services =  { '1min Loadavg': 'loadavg_1min', 'Cpu Idle Pct': 'cpu_ssCpuIdle' }
stg_services =  { '1min Loadavg': 'loadavg_1min', 'Cpu Idle Pct': 'cpu_ssCpuIdle' }
basic_commands = {'What am I':'whatami','Puppetsync':'puppetsync'}
asx_commands = {'What am I':'whatami','Puppetsync':'puppetsync'}
dev_commands = {'What am I':'whatami','Puppetsync':'puppetsync'}
qas_commands = {'What am I':'whatami','Puppetsync':'puppetsync'}
awr_commands = {'What am I':'whatami','Puppetsync':'puppetsync'}
pup_commands = {'What am I':'whatami','Puppetsync':'puppetsync'}
ser_commands = {'What am I':'whatami','Yum Update':'yum_update'}
cms_commands = {'What am I':'whatami','Yum Update':'yum_update'}
kss_commands = {'What am I':'whatami','Yum Update':'yum_update'}
adm_commands = {'What am I':'whatami','Yum Update':'yum_update'}
dbs_commands = {'What am I':'whatami','Yum Update':'yum_update'}
stg_commands = {'What am I':'whatami','Yum Update':'yum_update'}
queue_commands = {'Dass High Index':'dassRestartonHighIndex'}
rabbit_commands = {'Puppetsync':'puppetsync','Dass High Index':'dassRestartonHighIndex'}
queuem_commands = {'Puppetsync':'puppetsync','SC Rsync to Akamai':'tfound-akamai-sync','Start Corejobs':'corejobsstart','Stop Corejobs':'corejobsstop','Start Memcached':'memcached_start','Stop Memcached':'memcached_stop'}
web_commands = {'Restart Apache':'apache_restart'}
webonly_commands = {'Puppetsync':'puppetsync','Start Apache':'apachestart','Stop Apache':'apachestop','Start Memcached':'memcached_start','Stop Memcached':'memcached_stop'}
search_commands = {'Start Memcached':'memcached_start','Stop Memcached':'memcached_stop','Restart Dasserver':'dasserver_restart'}
docbase1_commands = {'What am I':'whatami','Puppetsync':'puppetsync'}
webdocbase_commands = {'Start Apache':'apachestart','Stop Apache':'apachestop','Start Memcached':'memcached_start','Stop Memcached':'memcached_stop','Start MongoS':'mongosstart','Stop MongoS':'mongosstop'}
 
prod_dict = { 'Production': 'prod', 'Staging': 'staging', 'QA': 'qa','Development': 'dev' }
server_dict = {'Webonly': 'webonly', 'Mongo Standalone': 'docbase', 'MongoC': 'docbasec', 'MongoD': 'docbased', 'Mongo ReplSet': 'docbase1', 'MongoS': 'docbases','Web and Search': 'web', 'Corejobs/Rabbit': 'queue', 'Corejobs': 'queuem', 'Search': 'search', 'Rabbit': 'rabbit', 'Mongo': 'mongo', 'Corejobs': 'corejobs'}
